### ISSUE TITLE
Develop FractionBounce

### ISSUE THREAD

**Issue by ymoullec** [ritjoe/sugarizer-lite#18]
This issue will be used to discuss the delevopment of FractionBounce for Sugarizer.

**Comment by ymoullec** [comment]
I have started setting up the **toolbar** for the activity. It now contains the same basic elements as the original activity, including the **settings palette** contents.
There is still some work to do on the layout of the palette. Also the "choose ball" and "choose background" buttons respectively don't expand to a list of balls and backgrounds yet.
The buttons don't do anything at the moment.

These changes have been pushed to [a new branch](https://github.com/ritjoe/sugarizer-lite/commits/FractionBounce-ymoullec).

**Comment by DennisSSDev** [comment]
Currently taking a look at our available documentation and I'll list out our feature mvp

**Comment by DennisSSDev** [comment]
MVP:
- A ball that translates downwards. Can be controlled by the left and right arrow keys.
  - Text denoting a fraction appears on top of the ball.
- Three sections on the bottom of the screen that is divided from 0 to 1.
- A scoreboard that keeps track of correct answers (at first just track correct and wrong answers)
- A simple game state machine that controls the flow of the game and generates the fraction numbers. How it would look like:
  - Has the player clicked on the ball? Yes -> start the gameplay loop + generate a fraction on the ball + allow the ball to start translating + allow for the bounds check to detect if the ball hit the bottom of the screen
  - Has the ball reached the bottom of the screen? Yes -> check if the location of the screen is correct according to the fraction and add / remove points accordingly.

**Comment by ritjoe** [comment]
I want to note the corresponding activity description issue 

https://github.com/ritjoe/sugarizer-lite/issues/13

as participants in each issue can earn credit working across the lines with their counterparts in the other, corresponding issue (developers seeking or offering feedback from/to describers and vice versa).

**Comment by DennisSSDev** [comment]
I thought it would not be trivial to render text in canvas but it seems fairly goddamn easy lol:
https://www.w3schools.com/graphics/canvas_text.asp

**Comment by DennisSSDev** [comment]
The main gameplay loop has been finished on [my branch](https://github.com/ritjoe/sugarizer-lite/tree/FractionBounce-DennisSSDev).
What I believe we are missing for the final deliverable are cosmetics, some sound effects and the display of the results. At the moment the only feedback the user gets for guessing right is a console log

**Comment by DennisSSDev** [comment]
Finished the cosmetics part. 

The only part we left out was the tedious ones where you pick out how the ball looks and the background change. 

It's very easy to do, but it's repetitive and doesn't affect the final gameplay experience

**Comment by DennisSSDev** [comment]
We'll now go through the process of merging into master
