### ISSUE TITLE
Can't Add a Wiki Page

### ISSUE THREAD

**Issue by iclare** [ritjoe/sugarizer-lite#6]
I'm not seeing the button to create a new page. This is the task table I was going to post.

| Project name   | Language (py or js) | analyze? (X for yes) <-- either | or --> develop? (X for yes) |
|----------------|---------------------|---------------------------------|-----------------------------|
| Fractionauts   | Python              |                                 | X                           |
| Lemonade-Stand | Python              |                                 | X                           |
| Fractionators  | JavaScript          | X                               |                             |
| FoodChain      | JavaScript          | X                               |                             |

**Comment by ritjoe** [comment]
On Tue, Apr 14, 2020 at 01:12:39PM -0700, Ian Clare wrote:
> I'm not seeing the button to create a new page. 

https://github.com/ritjoe/sugarizer-lite/issues/4#issuecomment-611853624

https://github.com/ritjoe/sugarizer-lite/issues/1#issuecomment-613106450


rit-foss.2020-04-06-13.00.log.txt:13:10:29 <dzho> I've issued github collaborator invitations to everyone

rit-foss.2020-04-10-13.02.log.txt:13:26:29 <dzho> jrtechs: I am *trying* to give everyone access to ritjoe/sugarizer-lite/wiki via invitations to collaborate


> This is the task table I was going to post.

I took the liberty of pulling a task table from your journal and tried to incorporate it as best I could in the overall assignments table, here:

https://github.com/ritjoe/sugarizer-lite/wiki/final-projects-20200414

**Comment by iclare** [comment]
Strange, I never received a collaborator invite for multiple repos this week. The notifications never came through on GitHub and I never received emails about them.

**Comment by iclare** [comment]
Closing since this seems to be an issue on my end / github
